### ISSUE TITLE
[Question] Shooting NPC

### ISSUE THREAD

**Issue by doreto** [Open-GTO/FCNPC#10]
I've downloaded the plugin and started bg(bodyguard) example script and tested npc shooting and notice they shoot very fast and make my question how good are npc shooting other players. Can they be used for server if their fire rate is lowered (if possible).

**Comment by ziggi** [comment]
You can use FCNPC_SetWeaponShootTime(npcid, weaponid, time);

**Comment by doreto** [comment]
Sweat :+1: did know about this. I guess time is in miliseconds and where this have to be places in `OnGameModeInit` or whatver i call `FCNPC_AimAt`

**Comment by ziggi** [comment]
Yes, time is in milliseconds. It can be placed anywere. Also you can set the default value (apply on each NPC) by `FCNPC_SetWeaponDefaultInfo(weaponid, reload_time = -1, shoot_time = -1, clip_size = -1);`
