### ISSUE TITLE
NPC is invulnerable when is set to false

### ISSUE THREAD

**Issue by doreto** [Open-GTO/FCNPC#14]
Like title say FNPC is invulnerable even when is set to be off. Also notice because of this you can't set FNPC health and aways returning 100.000. I was using Bodyguards filterscript when i found it.

**Comment by doreto** [comment]
![grand theft auto san andreas 04 06 2016 - 19 34 28 01](https://cloud.githubusercontent.com/assets/4704339/14324730/b9d5eece-fc2e-11e5-8bda-af33b31c42b1.png)

**Comment by ziggi** [comment]
FCNPC_OnTakeDamage should return 1 for take effect.

**Comment by doreto** [comment]
Everything work fine now. Thanks again :)
