### ISSUE TITLE
FCNPC crash

### ISSUE THREAD

**Issue by long76** [Open-GTO/FCNPC#16]
=========================== FCNPC Exception Handler ============================
Address: 0x6CEB2FF1

Registers:
EAX: 0x00000000 - EBX: 0x00000000 - ECX: 0x0E05F32C - EDX: 0x00000001
ESI: 0x00000000 - EDI: 0xe05f308 - EBP: 0x0018FD1C - ESP: 0x0018FCF0

Stack:
0x0: 0x044492D0 - 0x4: 0x00000168 - 0x8: 0x021EF598 - 0xC: 0x0018FD44 - 0x10: 0x6D15A573 - 0x14: 0x0018FD50
0x18: 0x00000001 - 0x1C: 0x00691848 - 0x20: 0x00000000

Information:
  System: Windows
  SA-MP: 0.3.7 R2-1
  FCNPC: 1.0.5

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466570
  FUNC_CPlayer__Kill: 0x484620
  FUNC_CPlayer__EnterVehicle: 0x484c70
  FUNC_CPlayer__ExitVehicle: 0x484f50
  FUNC_CPlayer__SpawnForWorld: 0x486d30
  FUNC_GetVehicleModelInfo: 0x488240
  FUNC_CConsole__GetIntVariable: 0x48b5b0
  FUNC_ClientJoin_RPC: 0x4918f0

Pointers:
  VAR_ServerAuthentication: 0x4f5fe8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5
=========================== FCNPC Exception Handler ============================

**Comment by ziggi** [comment]
I can't help without your Pawn script.

**Comment by ziggi** [comment]
Closed because I didn't get confirmation
