### ISSUE TITLE
Crashing at startup 

### ISSUE THREAD

**Issue by RockySawa** [Open-GTO/FCNPC#17]
hello, every time i start FCNPC my samp_server.exe closes and a new file "fcnpc-crash" gets created. 
I use the latest plugin and include, i put the require callbacks in the gamemode. Can you help, please?

**Comment by RockySawa** [comment]
======================== FCNPC Exception Handler ===============================
Address: 0x67DC72C6

Registers:
EAX: 0x082F0678 - EBX: 0x00000001 - ECX: 0x082F0678 - EDX: 0x00000000
ESI: 0x00000000 - EDI: 0x5f - EBP: 0x61442F73 - ESP: 0x00515C08

Stack:
0x0: 0x0000786D - 0x4: 0x00000000 - 0x8: 0x00000000 - 0xC: 0x00000000 - 0x10: 0x00000000 - 0x14: 0x00000000
0x18: 0x00000000 - 0x1C: 0x00000000 - 0x20: 0x00000000

Functions:
FUNC_CPlayerPool__DeletePlayer: 0x466570
FUNC_CPlayer__Kill: 0x484620
FUNC_CPlayer__EnterVehicle: 0x484c70
FUNC_CPlayer__ExitVehicle: 0x484f50
FUNC_CPlayer__SpawnForWorld: 0x486d30
FUNC_GetVehicleModelInfo: 0x488240
FUNC_CConsole__GetIntVariable: 0x48b5b0
FUNC_ClientJoin_RPC: 0x4918f0


Pointers:
VAR_ServerAuthentication: 0x4f5fe8
VAR_NetVersion: 0xfd9


Offsets:
OFFSET_RemoteSystemManager: 0x33c
OFFSET_RemoteSystemSize: 0xcb8
OFFSET_RemoteSystem__ConnectMode: 0xcb0
OFFSET_RemoteSystem__Unknown: 0xcb5
======================== FCNPC Exception Handler ===============================

**Comment by ziggi** [comment]
This crash log says that you using not last version of this plugin.

**Comment by RockySawa** [comment]
Could i know the last plugin link, Please? be cause i downloaded it from the thread at samp forums.

**Comment by ziggi** [comment]
@RockySawa https://github.com/Open-GTO/FCNPC/releases
