### ISSUE TITLE
NPC Kill player doesn't call OnPlayerDeath

### ISSUE THREAD

**Issue by WoutProvost** [Open-GTO/FCNPC#18]
Since the latest release, when an NPC kills a player, the OnPlayerDeath callback is not called.

**Comment by ziggi** [comment]
I tested it, and everything works great. FCNPC does not have any hooks for OnPlayerDeath and this callback can not be broken by the plugin.

**Comment by WoutProvost** [comment]
Discovered the cause, it's because of YSF 2.2. Somehow whenever I update YSF to the latest version, this problem happens again. It was broken in R17, fixed in R18, now broken again. Sigh :(

**Comment by WoutProvost** [comment]
I redownloaded YSF 2.2 and guess what, now it magically works! Even though it is the same version! The inconsistency with that plugin baffles my mind. I've just wasted so much time doing basically nothing.
