### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by Alf21** [Open-GTO/FCNPC#4]
Thats not an issue, but i want to ask whether you can implement FCNPC_GetWorld(int npcid) and FCNPC_SetWorld(int npcid, int worldId) ? :)

**Comment by ziggi** [comment]
Default [S/G]etPlayerVirtualWorld functions works perfect. But I will added these functions to get similar code style.
```Pawn
native FCNPC_SetWorld(npcid, worldid) = SetPlayerVirtualWorld;
native FCNPC_GetWorld(npcid) = GetPlayerVirtualWorld;
```
